# This file defines the labels for the repository
# Use with GitHub CLI: gh label import labels.yml
# Or manually create using the configuration below

# Issue Types
- name: bug
  color: d73a4a
  description: Something isn't working

- name: enhancement
  color: a2eeef
  description: New feature or request

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: question
  color: d876e3
  description: Further information is requested

- name: security
  color: ee0701
  description: Security-related issue

# Priority Labels
- name: priority/critical
  color: b60205
  description: Critical priority - requires immediate attention

- name: priority/high
  color: d93f0b
  description: High priority

- name: priority/medium
  color: fbca04
  description: Medium priority

- name: priority/low
  color: 0e8a16
  description: Low priority

# Status Labels
- name: needs-triage
  color: ededed
  description: Needs initial review and categorization

- name: confirmed
  color: 215cea
  description: Issue has been confirmed/reproduced

- name: in-progress
  color: fef2c0
  description: Currently being worked on

- name: blocked
  color: b60205
  description: Blocked by another issue or external dependency

- name: needs-info
  color: ffffff
  description: Additional information needed from reporter

- name: wontfix
  color: ffffff
  description: This will not be worked on

- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists

- name: invalid
  color: e4e669
  description: This doesn't seem right

# Component Labels
- name: component/ui
  color: 5319e7
  description: Related to the user interface

- name: component/api
  color: 5319e7
  description: Related to API routes and endpoints

- name: component/auth
  color: 5319e7
  description: Related to authentication and authorization

- name: component/database
  color: 5319e7
  description: Related to database and data layer

- name: component/ai
  color: 5319e7
  description: Related to AI/LLM functionality

- name: component/integrations
  color: 5319e7
  description: Related to third-party integrations

# Effort Labels
- name: effort/small
  color: c5def5
  description: "Estimated effort: less than 1 day"

- name: effort/medium
  color: c5def5
  description: "Estimated effort: 1-3 days"

- name: effort/large
  color: c5def5
  description: "Estimated effort: more than 3 days"

# Good First Issue Labels
- name: good first issue
  color: 7057ff
  description: Good for newcomers

- name: help wanted
  color: 008672
  description: Extra attention is needed

# Release Labels
- name: breaking-change
  color: ee0701
  description: Introduces a breaking change

- name: needs-release-notes
  color: 0e8a16
  description: Should be mentioned in release notes

# Technical Debt
- name: tech-debt
  color: ffa500
  description: Technical debt or refactoring needed

- name: performance
  color: ff69b4
  description: Performance-related issue or improvement

- name: testing
  color: bfd4f2
  description: Related to tests or testing infrastructure
