// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv dotenv-expand
import { config } from "dotenv";
import { expand } from "dotenv-expand";
import { defineConfig, env } from "prisma/config";

// Load from .env.local first, then fall back to .env
expand(config({ path: ".env.local" }));
expand(config({ path: ".env" }));

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
