name: Documentation Issue
description: Report missing, incorrect, or unclear documentation
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Please describe the issue or suggestion.

  - type: dropdown
    id: type
    attributes:
      label: Documentation Issue Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated information
        - Unclear or confusing content
        - Typo or grammar issue
        - Missing code examples
        - Broken links
        - Suggestion for improvement
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is this documentation issue? Provide a file path or URL.
      placeholder: e.g., README.md or https://docs.example.com/page
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What does the current documentation say? (if applicable)
      placeholder: Quote or describe the current content...
    validations:
      required: false

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Change
      description: What should the documentation say instead?
      placeholder: Describe or write out the suggested content...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context that might be helpful.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to submit a PR to fix this documentation issue
          required: false
