name: Question
description: Ask a question about project-etna
title: "[Question]: "
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're happy to help! Please provide as much context as possible.
        
        **Note:** For general discussions, consider using GitHub Discussions instead.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category does your question fall under?
      options:
        - Setup/Installation
        - Configuration
        - Usage/How-to
        - Architecture/Design
        - Integration
        - Deployment
        - Performance
        - Security
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context that might help us answer your question.
      placeholder: "What are you trying to accomplish? What have you tried so far?"
    validations:
      required: false

  - type: textarea
    id: research
    attributes:
      label: What I've Tried
      description: What resources have you already checked?
      placeholder: |
        - Read the README
        - Searched existing issues
        - Checked documentation
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched for similar questions in existing issues
          required: true
